# Default values for science-map
# This is a YAML-formatted file.

replicaCount: 3

image:
  repository: science-map
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: science-map.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: science-map-tls
      hosts:
        - science-map.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables
env:
  NODE_ENV: "production"
  PORT: "3000"

# Secrets
secrets:
  jwtSecret: "your-jwt-secret-key"
  jwtRefreshSecret: "your-jwt-refresh-secret-key"

# Frontend configuration
frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: science-map/frontend
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: science-map.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: science-map-tls
        hosts:
          - science-map.com
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

# API Gateway configuration
apiGateway:
  enabled: true
  replicaCount: 3
  image:
    repository: science-map/api-gateway
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: api.science-map.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: science-map-tls
        hosts:
          - api.science-map.com
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

# Graph Service configuration
graphService:
  enabled: true
  replicaCount: 2
  image:
    repository: science-map/graph-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 512Mi

# Search Service configuration
searchService:
  enabled: true
  replicaCount: 2
  image:
    repository: science-map/search-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    limits:
      cpu: 600m
      memory: 512Mi
    requests:
      cpu: 300m
      memory: 256Mi

# Auth Service configuration
authService:
  enabled: true
  replicaCount: 2
  image:
    repository: science-map/auth-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi

# Jobs Service configuration
jobsService:
  enabled: true
  replicaCount: 2
  image:
    repository: science-map/jobs-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    limits:
      cpu: 600m
      memory: 512Mi
    requests:
      cpu: 300m
      memory: 256Mi

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres"
    username: "sciencemap"
    password: "sciencemap"
    database: "sciencemap"
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: true
    password: "redis-password"
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

# Kafka configuration
kafka:
  enabled: true
  auth:
    clientProtocol: "plaintext"
  persistence:
    enabled: true
    size: 20Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  zookeeper:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
    adminPassword: "admin"
