global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'graph-service'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'search-service'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:3004']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'jobs-service'
    static_configs:
      - targets: ['host.docker.internal:3005']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
