groups:
- name: science-map-alerts
  rules:
  - alert: ServiceDown
    expr: up{job=~"science-map-.*"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.job }} is down"
      description: "Service {{ $labels.job }} has been down for more than 1 minute."

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High error rate for {{ $labels.job }}"
      description: "Error rate is {{ $value }} errors per second for {{ $labels.job }}"

  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response time for {{ $labels.job }}"
      description: "95th percentile response time is {{ $value }}s for {{ $labels.job }}"

  - alert: HighMemoryUsage
    expr: process_resident_memory_bytes / 1024 / 1024 / 1024 > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage for {{ $labels.job }}"
      description: "Memory usage is {{ $value }}GB for {{ $labels.job }}"

  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage for {{ $labels.job }}"
      description: "CPU usage is {{ $value }}% for {{ $labels.job }}"

  - alert: DatabaseConnectionPoolExhausted
    expr: database_connections_active / database_connections_max > 0.9
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Database connection pool nearly exhausted for {{ $labels.job }}"
      description: "Connection pool usage is {{ $value }}% for {{ $labels.job }}"

  - alert: LowCacheHitRate
    expr: rate(cache_hits_total[5m]) / rate(cache_requests_total[5m]) < 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low cache hit rate for {{ $labels.job }}"
      description: "Cache hit rate is {{ $value }}% for {{ $labels.job }}"

  - alert: ServiceUnavailable
    expr: up{job=~"science-map-.*"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.job }} is unavailable"
      description: "Service {{ $labels.job }} has been down for more than 30 seconds"
