name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm -w run -r type-check

      - name: Lint
        run: pnpm -w run -r lint

      - name: Format Check
        run: pnpm -w run -r format:check

      - name: Build
        run: pnpm -w run -r build

      - name: Test
        run: pnpm -w run -r test -- --ci --reporters=default --reporters=jest-junit || true

      - name: Quality Check
        run: pnpm -w run quality:check

      - name: Snyk Open Source (optional)
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: snyk/actions/node@master
        continue-on-error: true # Allow pipeline to pass even if Snyk fails
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --all-projects --prune-repeated-subdependencies

      - name: Trivy Container Scan (optional)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'your-docker-image-name:latest' # Replace with actual image name
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
